export const BARANGAYS = [
  "Bagumbayan",
  "Balading",
  "Banao",
  "Batbat",
  "Calzada (Pob.)",
  "Carriedo (Pob.)",
  "Doña Tomasa (Pob.)",
  "Ilawod West (Pob.)",
  "Ilawod Pob. (Ilawod East)",
  "Lomacao",
  "Maipon",
  "Malabnig",
  "Masarawag",
  "Mauraro",
  "Maybato",
  "Morera",
  "Muladbucad Grande",
  "Muladbucad Pequeño",
  "Pagpanamitan",
  "Paulba",
  "Quitinday East",
  "Quitinday West",
  "Rizal",
  "San Jose (Pob.)",
  "San Rafael (Pob.)",
  "Sinungtan",
  "Sua",
  "Tandarora",
  "Travesia (Pob.)",
  "Trece Martires (Pob.)",
];
