// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DIRECT_URL"), // Direct connection for Prisma CLI (migrations, db push, etc.)
    // App runtime uses DATABASE_URL (pooler) via PrismaClient in lib/prisma.ts
  },
});
